### ISSUE TITLE
How to set the languages dynamically on setLocale

### ISSUE THREAD

**Issue by sivabalan02** [funktionswerk/hapi-i18n#12]
Here is my code

```
const register = (server, options, next) => {
	server.register(
		{
			register     : require('hapi-i18n'),
			options      : {
				directory  : __dirname + "/../../locales/backend",
				locales    : ['en'],
			},
			defaultLocale: "ar"
		}
	);

	next();
};

register.attributes = {
	name: 'Internationalization'
};

module.exports = register;
```

Here in my options locales, comes from database as a dynamic. How can i achieve that.

**Comment by funktionswerk** [comment]
Hi sivabalan,

The options are passed to mashpie's i18n module (https://github.com/mashpie/i18n-node). I guess you have to contact him for dynamic support. Alternatively I can think of reading the translations from DB and write them to the locales directory before starting the app.

**Comment by sivabalan02** [comment]
@funktionswerk because of the asynchronous i can't stop the flow. I tried to set the locale option from the db itself it doesn't work

**Comment by funktionswerk** [comment]
Can you:

1. Connect to DB
2. Read locales and write as JSON to locales directory
4. Initialize hapi-i18n
3. Start the server

?
