### ISSUE TITLE
accept-language : fa-IR not working

### ISSUE THREAD

**Issue by jahangirahmad** [funktionswerk/hapi-i18n#15]
I send accept-language "fa-IR" to hapi-js api.
here hapi-js plugin options:
<pre>
{
    register: i18n,
    options : {
      locales            : ['en', 'fa-IR'],
      directory          : __dirname + '/locales',
      languageHeaderField: 'accept-language'
    }
 }
</pre>

This code does not detect locale, and set undefined in request.locale.
but if if configure locales :['en', 'fa-ir'], it works.
what should i do??

**Comment by kaywolter** [comment]
If it works: Configure the locales array with 'fa-ir'. Or is there a problem with that solution?

**Comment by jahangirahmad** [comment]
it's ok that use 'fa-ir' in my configuration file. But somewhere else (much) i used fa-IR in codes and database
